Gustavo Javier Garcia Salas Rodriguez
999007128
```{r}
library(tidyverse)

diamonds <- read.csv("diamonds.csv")
str(diamonds)
```

```{r}
#1ST SECTION
#Dispersion

ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point()
```
```{r}
ggplot(diamonds, aes(x = carat, y = price, color = clarity)) + 
  geom_point()
```

```{r}
#2nd Section
#Histogram

ggplot(diamonds, aes(x = price)) + 
  geom_histogram(bins = 40)
```
```{r}
ggplot(diamonds, aes(x = price)) +
  geom_histogram(bins = 40) +
  scale_x_log10()
```
```{r}
#3rd Section
#Boxplots

ggplot(diamonds, aes(x = cut, y = price)) + 
  geom_boxplot() +
  scale_y_log10()
```
```{r}
ggplot(diamonds, aes(x = cut, y = price, fill = cut)) + 
  geom_boxplot() +
  scale_y_log10()
```
```{r}
#4th Section
#Faceting

filtered_price <- diamonds %>%
  filter(price > 1000 & cut %in% c("Good", "Ideal", "Premium"))
filtered_price
```
```{r}
ggplot(filtered_price, aes(x = cut, y = depth)) + 
  geom_col() +
  facet_wrap(~ clarity)
```
```{r}
ggplot(filtered_price, aes(x = cut, y = depth, fill = clarity)) + 
  geom_col() +
  facet_wrap(~ clarity)
```
```{r}
#Grouping and summarizing
#1

median_dimension_diamond <- diamonds %>%
  group_by(cut) %>%
  summarize(mediaX = mean(x), mediaY = mean(y), mediaZ = mean(z))
median_dimension_diamond
```
```{r}
#2

cut_premium <- diamonds %>%
  filter(cut == "Premium") %>%
  group_by(clarity) %>%
  summarize(minPrice = min(price), maxPrice = max(price))
cut_premium
```
```{r}
#3
ggplot(cut_premium, aes(x = clarity, y = maxPrice, fill = clarity)) +
  geom_col()
```

