Gustavo Javier Garcia Salas Rodriguez
999007128
```{r}
library(tidyverse)

questions <- read.csv("questions.csv")
answers <- read.csv("answers.csv")
tags <- read.csv("tags.csv")
question_tags <- read.csv("question_tags.csv")

#1
questions_with_tags <- left_join(question_tags, questions, by = c("question_id" = "id"))
questions_with_tags <- left_join(questions_with_tags, tags, by = c("question_id" = "id"))
questions_with_tags <- questions_with_tags %>%
  replace_na(list(tag_name="only-r"))

questions_with_tags
```
```{r}
#2

questions_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score = sum(score)) %>%
  arrange(desc(mean_score))
```
```{r}
#3

questions
answers

questions %>%
  inner_join(answers, by = c("id" = "question_id"), suffix=c("_question", "_answer")) %>%
  mutate(gap = as.Date(creation_date_answer) - as.Date(creation_date_question))
```
```{r}
#4

answer_counts <- answers %>%
  count(question_id)
answer_counts

question_answer_counts <- questions %>%
  left_join(answer_counts, by = c("id" = "question_id")) %>%
  replace_na(list(n = 0))
question_answer_counts
```
```{r}
#5

question_tags %>%
  inner_join(question_answer_counts, by = c("question_id" = "id")) %>%
    inner_join(tags, by = c("tag_id" = "id"))
```

